// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SelfHostLlm.Persistence;

#nullable disable

namespace SelfHostLlm.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922194306_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claim");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claim_role_id");

                    b.ToTable("role_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claim_user_id");

                    b.ToTable("user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_user_id");

                    b.ToTable("user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_token");

                    b.ToTable("user_token", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Access.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("key_hash")
                        .IsFixedLength();

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_api_key");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_api_key_tenant_id_id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_key_key_hash");

                    b.HasIndex("TenantId", "ConsumerId")
                        .HasDatabaseName("ix_api_key_tenant_id_consumer_id");

                    b.ToTable("api_key", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Access.Consumer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_consumer");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_consumer_tenant_id_id");

                    b.ToTable("consumer", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Access.Quota", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<int?>("MaxConcurrentRequests")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_requests");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TokensPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_per_minute");

                    b.Property<long?>("TokensPerMonth")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_per_month");

                    b.HasKey("Id")
                        .HasName("pk_quota");

                    b.HasIndex("ConsumerId")
                        .IsUnique()
                        .HasDatabaseName("ix_quota_consumer_id");

                    b.HasIndex("TenantId", "ConsumerId")
                        .HasDatabaseName("ix_quota_tenant_id_consumer_id");

                    b.ToTable("quota", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_value");

                    b.Property<string>("BeforeValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_value");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_log_actor_user_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_tenant_id_occurred_at");

                    b.ToTable("audit_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_action", "action IN ('Create', 'Update', 'Delete', 'Revoke', 'Enable', 'Disable', 'AssignRole', 'Login')");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("api_key_encrypted");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("health_status");

                    b.Property<DateTimeOffset?>("LastProbedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_probed_at");

                    b.Property<int?>("LatencyMsP50")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms_p50");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid?>("ModelVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_version_id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("RemoteModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("remote_model_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_deployment");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_deployment_tenant_id_id");

                    b.HasIndex("TenantId", "ModelId")
                        .HasDatabaseName("ix_deployment_tenant_id_model_id");

                    b.HasIndex("TenantId", "ModelVersionId")
                        .HasDatabaseName("ix_deployment_tenant_id_model_version_id");

                    b.HasIndex("TenantId", "ProviderId")
                        .HasDatabaseName("ix_deployment_tenant_id_provider_id");

                    b.HasIndex("ProviderId", "Address", "RemoteModelName")
                        .IsUnique()
                        .HasDatabaseName("ix_deployment_provider_id_base_url_remote_model_name");

                    b.ToTable("deployment", null, t =>
                        {
                            t.HasCheckConstraint("ck_deployment_health_status", "health_status IN ('Unknown', 'Healthy', 'Unhealthy')");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContextLength")
                        .HasColumnType("integer")
                        .HasColumnName("context_length");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParamSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("param_size");

                    b.Property<string>("Quantization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quantization");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string[]>("_capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.Property<List<string>>("_taskTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("task_tags");

                    b.HasKey("Id")
                        .HasName("pk_model");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_model_tenant_id_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_model_tenant_id_name");

                    b.ToTable("model", null, t =>
                        {
                            t.HasCheckConstraint("ck_model_capabilities", "capabilities <@ ARRAY['Chat', 'Embedding', 'Vision']::text[]");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Models.ModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdapterUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("adapter_uri");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TrainingJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_job_id");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version_tag");

                    b.Property<string>("_evalMetrics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("eval_metrics");

                    b.HasKey("Id")
                        .HasName("pk_model_version");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_model_version_tenant_id_id");

                    b.HasIndex("ModelId", "VersionTag")
                        .IsUnique()
                        .HasDatabaseName("ix_model_version_model_id_version_tag");

                    b.HasIndex("TenantId", "ModelId")
                        .HasDatabaseName("ix_model_version_tenant_id_model_id");

                    b.HasIndex("TenantId", "TrainingJobId")
                        .HasDatabaseName("ix_model_version_tenant_id_training_job_id");

                    b.ToTable("model_version", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Providers.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_provider");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_provider_tenant_id_id");

                    b.ToTable("provider", null, t =>
                        {
                            t.HasCheckConstraint("ck_provider_kind", "kind IN ('Ollama', 'Vllm', 'Tgi', 'LlamaCpp', 'Mlx', 'OpenAiCompatible')");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Rag.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id")
                        .HasName("pk_chunk");

                    b.HasIndex("DocumentId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_chunk_document_id_ordinal");

                    b.HasIndex("TenantId", "CollectionId")
                        .HasDatabaseName("ix_chunk_tenant_id_collection_id");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("ix_chunk_tenant_id_document_id");

                    b.ToTable("chunk", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Rag.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_overlap");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmbeddingDim")
                        .HasColumnType("integer")
                        .HasColumnName("embedding_dim");

                    b.Property<Guid>("EmbeddingModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("embedding_model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_collection");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_collection_tenant_id_id");

                    b.HasIndex("TenantId", "EmbeddingModelId")
                        .HasDatabaseName("ix_collection_tenant_id_embedding_model_id");

                    b.ToTable("collection", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_chunk_overlap", "chunk_overlap >= 0 AND chunk_overlap < chunk_size");

                            t.HasCheckConstraint("ck_collection_embedding_dim", "embedding_dim = 1024");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Rag.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("SourceUri")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_uri");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_document_tenant_id_id");

                    b.HasIndex("TenantId", "CollectionId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_document_tenant_id_collection_id_content_hash");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Routing.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VirtualModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("virtual_model_id");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_route");

                    b.HasIndex("TenantId", "DeploymentId")
                        .HasDatabaseName("ix_route_tenant_id_deployment_id");

                    b.HasIndex("TenantId", "VirtualModelId")
                        .HasDatabaseName("ix_route_tenant_id_virtual_model_id");

                    b.HasIndex("VirtualModelId", "DeploymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_route_virtual_model_id_deployment_id");

                    b.HasIndex("VirtualModelId", "Priority")
                        .HasDatabaseName("ix_route_virtual_model_id_priority");

                    b.ToTable("route", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Routing.VirtualModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("task");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_virtual_model");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_virtual_model_tenant_id_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_virtual_model_tenant_id_name");

                    b.ToTable("virtual_model", null, t =>
                        {
                            t.HasCheckConstraint("ck_virtual_model_task", "task IN ('Chat', 'Coding', 'Embedding', 'Summarization', 'Classification')");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_slug");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Training.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_uri");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_dataset");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_dataset_tenant_id_id");

                    b.ToTable("dataset", (string)null);
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Training.TrainingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_model_id");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("LogUri")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("log_uri");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("_hyperparameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hyperparameters");

                    b.HasKey("Id")
                        .HasName("pk_training_job");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_training_job_tenant_id_id");

                    b.HasIndex("TenantId", "BaseModelId")
                        .HasDatabaseName("ix_training_job_tenant_id_base_model_id");

                    b.HasIndex("TenantId", "DatasetId")
                        .HasDatabaseName("ix_training_job_tenant_id_dataset_id");

                    b.ToTable("training_job", null, t =>
                        {
                            t.HasCheckConstraint("ck_training_job_method", "method IN ('LoRA', 'QLoRA')");

                            t.HasCheckConstraint("ck_training_job_status", "status IN ('Queued', 'Running', 'Succeeded', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Usage.UsageAggregate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_start");

                    b.Property<long>("CompletionTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("completion_tokens");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("period");

                    b.Property<long>("PromptTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("prompt_tokens");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer")
                        .HasColumnName("request_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_usage_aggregate");

                    b.HasIndex("TenantId", "ConsumerId", "Period", "BucketStart")
                        .IsUnique()
                        .HasDatabaseName("ix_usage_aggregate_tenant_id_consumer_id_period_bucket_start");

                    b.ToTable("usage_aggregate", null, t =>
                        {
                            t.HasCheckConstraint("ck_usage_aggregate_period", "period IN ('Hour', 'Day', 'Month')");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Usage.UsageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("RequestedModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requested_model");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("Task")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("task");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TokensEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("tokens_estimated");

                    b.Property<bool>("UsedFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("used_fallback");

                    b.HasKey("Id")
                        .HasName("pk_usage_record");

                    b.HasIndex("TenantId", "ApiKeyId")
                        .HasDatabaseName("ix_usage_record_tenant_id_api_key_id");

                    b.HasIndex("TenantId", "DeploymentId")
                        .HasDatabaseName("ix_usage_record_tenant_id_deployment_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_usage_record_tenant_id_occurred_at");

                    b.ToTable("usage_record", null, t =>
                        {
                            t.HasCheckConstraint("ck_usage_record_task", "task IN ('Chat', 'Coding', 'Embedding', 'Summarization', 'Classification')");
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Persistence.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<List<string>>("_permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_role_normalized_name");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b1d0f7e-7a51-4c3e-9f0a-000000000001"),
                            ConcurrencyStamp = "0b1d0f7e-7a51-4c3e-9f0a-000000000001",
                            Name = "PlatformAdmin",
                            NormalizedName = "PLATFORMADMIN",
                            _permissions = new List<string> { "apikeys:manage", "audit:read", "consumers:read", "consumers:write", "deployments:read", "deployments:write", "models:read", "models:write", "providers:read", "providers:write", "quotas:read", "quotas:write", "rag:read", "rag:write", "rbac:manage", "routes:read", "routes:write", "tenants:manage", "training:read", "training:write", "usage:read" }
                        },
                        new
                        {
                            Id = new Guid("0b1d0f7e-7a51-4c3e-9f0a-000000000002"),
                            ConcurrencyStamp = "0b1d0f7e-7a51-4c3e-9f0a-000000000002",
                            Name = "TenantAdmin",
                            NormalizedName = "TENANTADMIN",
                            _permissions = new List<string> { "apikeys:manage", "audit:read", "consumers:read", "consumers:write", "deployments:read", "deployments:write", "models:read", "models:write", "providers:read", "providers:write", "quotas:read", "quotas:write", "rag:read", "rag:write", "rbac:manage", "routes:read", "routes:write", "training:read", "training:write", "usage:read" }
                        },
                        new
                        {
                            Id = new Guid("0b1d0f7e-7a51-4c3e-9f0a-000000000003"),
                            ConcurrencyStamp = "0b1d0f7e-7a51-4c3e-9f0a-000000000003",
                            Name = "Operator",
                            NormalizedName = "OPERATOR",
                            _permissions = new List<string> { "consumers:read", "deployments:read", "deployments:write", "models:read", "models:write", "providers:read", "providers:write", "quotas:read", "rag:read", "routes:read", "routes:write", "training:read", "usage:read" }
                        },
                        new
                        {
                            Id = new Guid("0b1d0f7e-7a51-4c3e-9f0a-000000000004"),
                            ConcurrencyStamp = "0b1d0f7e-7a51-4c3e-9f0a-000000000004",
                            Name = "Viewer",
                            NormalizedName = "VIEWER",
                            _permissions = new List<string> { "audit:read", "consumers:read", "deployments:read", "models:read", "providers:read", "quotas:read", "rag:read", "routes:read", "training:read", "usage:read" }
                        });
                });

            modelBuilder.Entity("SelfHostLlm.Persistence.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_app_user_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_normalized_user_name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_app_user_tenant_id");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SelfHostLlm.Persistence.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claim_role_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SelfHostLlm.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claim_app_user_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SelfHostLlm.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_login_app_user_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SelfHostLlm.Persistence.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("SelfHostLlm.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_app_user_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SelfHostLlm.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_token_app_user_user_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Access.ApiKey", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_tenant");

                    b.HasOne("SelfHostLlm.Domain.Access.Consumer", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ConsumerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_consumer_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Access.Consumer", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consumer_tenant");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Access.Quota", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quota_tenant");

                    b.HasOne("SelfHostLlm.Domain.Access.Consumer", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ConsumerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quota_consumer_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("SelfHostLlm.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_log_actor_user_id");

                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_tenant");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Deployments.Deployment", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_tenant");

                    b.HasOne("SelfHostLlm.Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_model_id");

                    b.HasOne("SelfHostLlm.Domain.Models.ModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_deployment_model_version_id");

                    b.HasOne("SelfHostLlm.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProviderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_provider_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Models.Model", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_model_tenant");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Models.ModelVersion", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_model_version_tenant");

                    b.HasOne("SelfHostLlm.Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_model_version_model_id");

                    b.HasOne("SelfHostLlm.Domain.Training.TrainingJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TrainingJobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_model_version_training_job_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Providers.Provider", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_provider_tenant");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Rag.Chunk", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chunk_tenant");

                    b.HasOne("SelfHostLlm.Domain.Rag.Collection", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CollectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunk_collection_id");

                    b.HasOne("SelfHostLlm.Domain.Rag.Document", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DocumentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunk_document_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Rag.Collection", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_collection_tenant");

                    b.HasOne("SelfHostLlm.Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EmbeddingModelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_collection_embedding_model_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Rag.Document", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_tenant");

                    b.HasOne("SelfHostLlm.Domain.Rag.Collection", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CollectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_collection_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Routing.Route", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_route_tenant");

                    b.HasOne("SelfHostLlm.Domain.Deployments.Deployment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeploymentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_route_deployment_id");

                    b.HasOne("SelfHostLlm.Domain.Routing.VirtualModel", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "VirtualModelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_route_virtual_model_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Routing.VirtualModel", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_virtual_model_tenant");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Training.Dataset", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dataset_tenant");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Training.TrainingJob", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_job_tenant");

                    b.HasOne("SelfHostLlm.Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BaseModelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_job_base_model_id");

                    b.HasOne("SelfHostLlm.Domain.Training.Dataset", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DatasetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_job_dataset_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Usage.UsageAggregate", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usage_aggregate_tenant");

                    b.HasOne("SelfHostLlm.Domain.Access.Consumer", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ConsumerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usage_aggregate_consumer_id");
                });

            modelBuilder.Entity("SelfHostLlm.Domain.Usage.UsageRecord", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usage_record_tenant");

                    b.HasOne("SelfHostLlm.Domain.Access.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ApiKeyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usage_record_api_key_id");

                    b.HasOne("SelfHostLlm.Domain.Deployments.Deployment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeploymentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usage_record_deployment_id");
                });

            modelBuilder.Entity("SelfHostLlm.Persistence.Identity.AppUser", b =>
                {
                    b.HasOne("SelfHostLlm.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
